/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MyModule"
 * 	found in "prova-asn1-schema.asn"
 * 	`asn1c -D new -no-gen-example`
 */

#ifndef	_MyInt_H_
#define	_MyInt_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MyInt */
typedef long	 MyInt_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_MyInt_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_MyInt;
asn_struct_free_f MyInt_free;
asn_struct_print_f MyInt_print;
asn_constr_check_f MyInt_constraint;
ber_type_decoder_f MyInt_decode_ber;
der_type_encoder_f MyInt_encode_der;
xer_type_decoder_f MyInt_decode_xer;
xer_type_encoder_f MyInt_encode_xer;
oer_type_decoder_f MyInt_decode_oer;
oer_type_encoder_f MyInt_encode_oer;
per_type_decoder_f MyInt_decode_uper;
per_type_encoder_f MyInt_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _MyInt_H_ */
#include <asn_internal.h>
