/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MyModule"
 * 	found in "prova-asn1-schema.asn"
 * 	`asn1c -D new -no-gen-example`
 */

#ifndef	_MyTypes_H_
#define	_MyTypes_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>
#include <BIT_STRING.h>
#include "MyInt.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum myBitString {
	myBitString_muxToken	= 0,
	myBitString_modemToken	= 1
} e_myBitString;

/* MyTypes */
typedef struct MyTypes {
	OBJECT_IDENTIFIER_t	 myObjectId;
	struct mySeqOf {
		A_SEQUENCE_OF(MyInt_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} mySeqOf;
	BIT_STRING_t	 myBitString;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MyTypes_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MyTypes;

#ifdef __cplusplus
}
#endif

#endif	/* _MyTypes_H_ */
#include <asn_internal.h>
