/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MyModule"
 * 	found in "prova-asn1-schema.asn"
 * 	`asn1c -D new -no-gen-example`
 */

#include "MyTypes.h"

static asn_TYPE_member_t asn_MBR_mySeqOf_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_MyInt,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_mySeqOf_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_mySeqOf_specs_3 = {
	sizeof(struct mySeqOf),
	offsetof(struct mySeqOf, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_mySeqOf_3 = {
	"mySeqOf",
	"mySeqOf",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_mySeqOf_tags_3,
	sizeof(asn_DEF_mySeqOf_tags_3)
		/sizeof(asn_DEF_mySeqOf_tags_3[0]), /* 1 */
	asn_DEF_mySeqOf_tags_3,	/* Same as above */
	sizeof(asn_DEF_mySeqOf_tags_3)
		/sizeof(asn_DEF_mySeqOf_tags_3[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_mySeqOf_3,
	1,	/* Single element */
	&asn_SPC_mySeqOf_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_MyTypes_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MyTypes, myObjectId),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"myObjectId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MyTypes, mySeqOf),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_mySeqOf_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mySeqOf"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MyTypes, myBitString),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"myBitString"
		},
};
static const ber_tlv_tag_t asn_DEF_MyTypes_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_MyTypes_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 2, 0, 0 }, /* myBitString */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 }, /* myObjectId */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 } /* mySeqOf */
};
static asn_SEQUENCE_specifics_t asn_SPC_MyTypes_specs_1 = {
	sizeof(struct MyTypes),
	offsetof(struct MyTypes, _asn_ctx),
	asn_MAP_MyTypes_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_MyTypes = {
	"MyTypes",
	"MyTypes",
	&asn_OP_SEQUENCE,
	asn_DEF_MyTypes_tags_1,
	sizeof(asn_DEF_MyTypes_tags_1)
		/sizeof(asn_DEF_MyTypes_tags_1[0]), /* 1 */
	asn_DEF_MyTypes_tags_1,	/* Same as above */
	sizeof(asn_DEF_MyTypes_tags_1)
		/sizeof(asn_DEF_MyTypes_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_MyTypes_1,
	3,	/* Elements count */
	&asn_SPC_MyTypes_specs_1	/* Additional specs */
};

