#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <stdbool.h>
#include "CAM.h"  // This will be generated by asn1c compiler
#include <GenerationDeltaTime.h>
#include <ItsPduHeader.h>
#include <CoopAwareness.h>
#include <HighFrequencyContainer.h>
#include "asn_application.h"
#include <sys/time.h>


typedef struct ritorno{
    asn_encode_to_new_buffer_result_t r;
    bool b;
} ritorno;

CAM_t* create_cam_message(int lat, int lon);
ritorno encode_cam_message(const CAM_t* cam);
void bin_to_hex(const unsigned char *bin, size_t bin_len, char **hex_str);
void process_hex_string(const char *hex_str);
