/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Cam"
 * 	found in "cam.asn"
 */

#include "CAM.h"

static asn_TYPE_member_t asn_MBR_CAM_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CAM, protocolVersion),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"protocolVersion"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CAM, subCauseCodeType),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"subCauseCodeType"
		},
};
static const ber_tlv_tag_t asn_DEF_CAM_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CAM_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 1 }, /* protocolVersion */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 0 } /* subCauseCodeType */
};
static asn_SEQUENCE_specifics_t asn_SPC_CAM_specs_1 = {
	sizeof(struct CAM),
	offsetof(struct CAM, _asn_ctx),
	asn_MAP_CAM_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_CAM = {
	"CAM",
	"CAM",
	&asn_OP_SEQUENCE,
	asn_DEF_CAM_tags_1,
	sizeof(asn_DEF_CAM_tags_1)
		/sizeof(asn_DEF_CAM_tags_1[0]), /* 1 */
	asn_DEF_CAM_tags_1,	/* Same as above */
	sizeof(asn_DEF_CAM_tags_1)
		/sizeof(asn_DEF_CAM_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_CAM_1,
	2,	/* Elements count */
	&asn_SPC_CAM_specs_1	/* Additional specs */
};

